# Generated by Django 5.2.1 on 2025-05-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birlik_raqami', models.CharField(max_length=50, unique=True)),
                ('nomi', models.CharField(max_length=100)),
                ('yaratilgan_vaqti', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['nomi'],
            },
        ),
    ]
