
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.fronted
    ports:
      - "5500:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    environment:
      - DJANGO_SETTINGS_MODULE=src.settings