# Generated by Django 5.2.1 on 2025-05-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=1, upload_to='user-imgs/'),
            preserve_default=False,
        ),
    ]
